### ISSUE TITLE
Added custom settings which will be ignored by git

### ISSUE THREAD

**Issue by mirelon** [DreamTeam2/frisbee-turnaje#1]

**Comment by matejka9** [comment]
? Co to je?

**Comment by mirelon** [comment]
Napriklad heslo k databaze

**Comment by matejka9** [comment]
Nerozumiem tomu co sa chce a jak to robit

**Comment by mirelon** [comment]
Tuto si zmazal .gitignore: https://github.com/DreamTeam2/frisbee-turnaje/commit/a777f965c8a76c0b859f2fd3c0511e317bf87a18 - preco?

Tuto je heslo k databaze: https://github.com/DreamTeam2/frisbee-turnaje/blob/master/Frisbee/Frisbee/settings.py

Heslo k databaze a ine custom overridy by mali byt v subore, ktory nie je v repozitari. Da sa to dosiahnut napr. pomocou gitignore.

**Comment by matejka9** [comment]
neviem preco som to zmazal nebol to zamer, problem je v tom ze ja som to sem nedaval a v mojom depozitary som to nemal a hlasilo mi to chyby ktore mi nesli vyriesit uz po comite a neslo ani mergnut, to som nevedel tato gitskupina mala byt pre nas a projekt sa tu povedone nemal davat mal sa odovzdavat Tebe, takze sa to  stalo proste kvoli neskusenosti

**Comment by mirelon** [comment]
To by som bol teda zvedavy, ako by to dopadlo, keby ste commitovali vsetci styria :)

**Comment by matejka9** [comment]
Zo zaciatku na nic kym by sme sa nenaucili :) zatial sme tu situaciu nemuseli riesit a teraz som ju neocakaval a robil som to vcera do 2hej rana takze som sa nechcel hrajkat s tym ze git mi este teraz nadava ze nieco nie je ok :laughing:

**Comment by mirelon** [comment]
Skusim to spravit podla tohto: http://fearofcode.github.io/blog/2013/01/15/how-to-scrub-sensitive-information-from-django-settings-dot-py-files/
