### ISSUE TITLE
Nefunguje diakritika, namiesto znakov s makcenmi sa uklada otaznik

### ISSUE THREAD

**Issue by mirelon** [DreamTeam2/frisbee-turnaje#6]
V logu je: Warning: Incorrect string value: '\xC4\x8D' for column 'priezvisko' at row 1
  return self.cursor.execute(query, args)

Moze to byt sposobene napr. tymto: http://stackoverflow.com/questions/2108824/mysql-incorrect-string-value-error-when-save-unicode-string-in-django

**Comment by matejka9** [comment]
V DB v mysql pri vytvarani databazy treba nastavit jazyk, to to vyriesi

**Comment by mirelon** [comment]
OK, upravil som readme: https://github.com/DreamTeam2/frisbee-turnaje/commit/2e93b143d35f1ecac515f1947c4d99a7e24d77bb
